apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app: hello
    tier: frontend
spec:
  containers:
    - name: hello
      image: hashicorp/http-echo
      args:
        - "-text=Hello from Kubernetes!"
        - "-listen=:8080"
      ports:
        - containerPort: 8080
